CoffeaTeam/coffea-casa

- .github/workflows/ci.yml
Needed for https://github.com/CoffeaTeam/coffea-casa/pull/27
> Add installation of patched distributed module to CI

- .github/workflows/ci.yml
- .github/workflows/dockerpublish.yml
- docker/coffea-casa-analysis/Dockerfile
- docker/coffea-casa-analysis/prepare-env.sh
- docker/coffea-casa/Dockerfile
- setup.py
Relevant GH issue: https://github.com/CoffeaTeam/coffea-casa/issues/24 https://github.com/CoffeaTeam/coffea-casa/issues/23 https://github.com/CoffeaTeam/coffea-casa/issues/21
Update: we are missing PR checks for images, to be added here.
> [Docker] Optimise docker images (first iteration)

- .github/workflows/dockerci.yml
- .github/workflows/dockerpublish.yml
- docker/coffea-casa-analysis/prepare-env.sh
- docker/coffea-casa-sidecar/Dockerfile
- docker/coffea-casa-sidecar/condor_config
- docker/coffea-casa-sidecar/config.d/01-red
- docker/coffea-casa-sidecar/config.d/04-red-submitter
- docker/coffea-casa-sidecar/config.d/05-red-external
- docker/coffea-casa-sidecar/config.d/99-t3
- docker/coffea-casa-sidecar/prepare-env.sh
- docker/coffea-casa/labextension.yaml
Side container for https://github.com/CoffeaTeam/coffea-casa/issues/6
> Add Coffea-casa sidecar container (runs in k8s)

- .github/workflows/ci.yml
- .github/workflows/dockerpublish.yml
- coffea_casa/jobqueue-coffea-casa.yaml
- docker/coffea-casa-analysis/Dockerfile
- docker/coffea-casa-analysis/supervisord.conf
- docker/coffea-casa/jobqueue-coffea-casa.yaml
- tests/test_config.py
Fixes: https://github.com/CoffeaTeam/jhub/issues/31
> Add supervisord configuration for sidecar

- docker/coffea-casa-analysis/Dockerfile
Fixes: https://github.com/CoffeaTeam/jhub/issues/37
> [JH-37]Name of Kubernetes worker should be unique

- docker/coffea-casa-analysis/prepare-env.sh
Changes addressing this specific issue: https://github.com/CoffeaTeam/coffea-casa/issues/74
> Updating paths in worker prepare_env

- coffea_casa/coffea_casa.py
- docker/coffea-casa-analysis/prepare-env.sh
- tests/test_coffeacasa.py
- tests/test_coffeacasa_args.py
> Test installation of package @ dask-worker via conda/pip

- .gitmodules
Part of https://github.com/CoffeaTeam/coffea-casa/pull/90
> Add coffea-casa-tutorials as a git submodule

- docs/cc_issues.rst
I completely missed the fact that there were no new lines after the issues on the issues page in the previous PR I put in (I'm still bad at this whole Sphinx thing). This should make it look a lot nicer!
> Issues Page - Add Newlines

- docs/index.rst
Reverts CoffeaTeam/coffea-casa#101
> Revert "Rendering code through nbsphinx"

- docker/coffea-casa/Dockerfile
- docker/coffea-casa/prepare-env.sh
- docker/coffea-casa/start.sh
> Adapting coffea-casa Docker image for compatibility with JupyterHub at the ElasticAF

- docker/coffea-casa-analysis/Dockerfile
- docker/coffea-casa/Dockerfile
> [security] we need to be sure that all packages are upgraded as well

- docker/coffea-casa/Dockerfile
- docker/coffea-casa/prepare-env.sh
- docker/coffea-casa/start.sh
Replaces #126 (I couldn't rebase it...)
Fixes https://github.com/CoffeaTeam/coffea-casa/issues/125
> [replaces #126] Source prepare-env.sh in the start.sh script to override possible leftovers from build

- docs/cc_user_ssl.rst
Here are some changes Rob wants to put in:
some updates to account wording, fix broken link to the servicex notebook and add one more example.
> some updates to the cc user ssl docs

- docker/coffea-casa-analysis-cc7/Dockerfile
- docker/coffea-casa-cc7/Dockerfile
> Misc fixes for Centos7 image

- docker/coffea-casa/Dockerfile
- docker/coffea-casa/build-skyhook.sh
Part of https://github.com/CoffeaTeam/coffea-casa/issues/196
> Add Skyhook support for CC scheduler image

- docker/coffea-casa-analysis-cc7/Dockerfile
- docker/coffea-casa-analysis/Dockerfile
- docker/coffea-casa-analysis/build-skyhook.sh
- docker/coffea-casa-analysis/ceph.conf
- docker/coffea-casa-analysis/keyring
- docker/coffea-casa-analysis/prepare-env.sh
- docker/coffea-casa-cc7/Dockerfile
- docker/coffea-casa/Dockerfile
- docker/coffea-casa/ceph.conf
- docker/coffea-casa/prepare-env.sh
> Add CEPH_CONF to be used for ceph configuration files

- docker/Dockerfile.cc-base-ubuntu
Add voms config files (synced from lxplus)
Should help with the [next issue](https://atlas-talk.sdcc.bnl.gov/t/unable-to-initialte-voms-proxy-or-access-cvmfs/179/5)
> Add voms config files (added from opensciencegrid/osg-vo-config)

- docker/Dockerfile.cc-centos7
- docker/Dockerfile.cc-centos7-skyhook
- docker/Dockerfile.cc-ubuntu
- docker/Dockerfile.cc-ubuntu-skyhook
- docker/README.md
> Fixing broken worker image used by dask jobqueue for scaling

- coffea_casa/coffea_casa.py
- docker/Dockerfile.cc-analysis-ubuntu
- docker/Dockerfile.cc-ubuntu
- docker/prepare-env/prepare-env-cc-analysis.sh
- docker/prepare-env/prepare-env-cc.sh
- tests/test_config.py
(available /etc/cmsaf-secrets/access_token)
Work from John Thiltges and Carl
> Testing new xcache with new pregenerated scitoken for it 

- .github/workflows/pypi-ci.yml
- coffea_casa/coffea_casa.py
- coffea_casa/jobqueue-coffea-casa.yaml
See relevant dask jobqueue changes: https://github.com/dask/dask-jobqueue/compare/0.7.4...0.8.2
> Update coffea_casa module to sync with dask jobqueue 0.8.2
