CoffeaTeam/coffea-casa

- docs/index.rst
The structure of coffea-casa-tutorials changed when Zora added the topcoffea analysis, and I'd forgotten to update the links in coffea-casa's index. That should be fixed now!
> Fixed broken link in index.rst

- docs/index.rst
I was able to get nbsphinx to render our example code in coffea-casa-tutorials/ locally after some small edits in the coffea-casa-tutorials/ repo, though I don't know if the fact that coffea-casa-tutorials/ is a linked subdirectory impacts the formatting on Github (and have no way of testing, other than this PR!)
With luck... everything will work.
> Rendering code through nbsphinx

- coffea_casa/jobqueue-coffea-casa.yaml
- docker/coffea-casa-analysis/Dockerfile
- docker/coffea-casa/Dockerfile
- docker/coffea-casa/jobqueue-coffea-casa.yaml
- docker/coffea-casa/prepare-env.sh
- tests/test_config.py
- ServiceX is available only from JH notebook for now
- testing coffea-casa dev instance without xrd-authz-plugin (with this setup xcache is disabled, but I need to find regression for combination of xrd-authz-plugin+xrootd5.2.0)
> [dev] Fix ServiceX conf file generation; testing coffea-casa dev instance without xrd-authz-plugin

- coffea_casa/__init__.py
- coffea_casa/plugin.py
Addresses #219 by including a new [plugins.py](https://github.com/Andrew42/coffea-casa/blob/dep-nanny-plugin/coffea_casa/plugin.py) file that provides a `NannyPlugin` that can install a locally specified pip installable package. The plugin can also be provided a list of individual python files (e.g. analysis specific processor definitions) that should be included alongside the main package.
This PR does not currently include a corresponding `pytest` test as it is unclear how to best setup the inputs for a useful unit test. I plan to make a github issue, which will link back to this PR, regarding the need for such a test, so that we don't forget.
There are a few other parts of coffea-casa that I would like to get feedback on if they should also be modified in this PR. These are related to …
> Add DistributedEnvironmentPlugin

- docs/cc_user.rst
I noticed (after seeing the new docs rendered) that I had forgotten to add the appropriate ATLAS-only notes for the sections I merged from the UChicago page. This is just a quick patch that fixes that.
> Standardizing the usage of "important" notes for ATLAS-only sections

- coffea_casa/coffea_casa.py
- docker/dask/jobqueue-coffea-casa.yaml
Following the problem discovered in https://github.com/CoffeaTeam/lpcjobqueue/pull/12 (@nsmith- 👍 )
> Update coffea-casa dask jobqueue cluster config file to match the new naming conventions in the recent dask_jobqueue release

- coffea_casa/coffea_casa.py
- coffea_casa/jobqueue-coffea-casa.yaml
- docker/Dockerfile.cc-analysis-ubuntu
- docker/Dockerfile.cc-ubuntu
- docker/dask/jobqueue-coffea-casa.yaml
For now, we are limited with `dask-jobqueue`==0.7.4. Moving to `dask-jobqueue`==0.8.0 will require updating the `coffea_casa` configuration (we have a chance to improve it!).
> Add Dask jobqueue 0.7.4 support

- docker/Dockerfile.cc-analysis-ubuntu
- docker/Dockerfile.cc-ubuntu
Looks like there were some changes in codebase which is incompatible to our current setup (we need more testing)
It will be expected to be fixed with https://github.com/CoffeaTeam/coffea-casa/issues/337
> For PyHEP we are going to use dask_jobqueue 0.7.3

- docker/Dockerfile.cc-analysis-centos7
- docker/Dockerfile.cc-analysis-ubuntu
- docker/Dockerfile.cc-base-centos7
- docker/Dockerfile.cc-base-ubuntu
Resolves #344
* `cabinetry` `v0.5.0+` requires `pyhf` `v0.7.x` which requires `jsonschema>=4.15.0`. Use `mamba` for the install of `cabinetry` to consolidate as many of the library requirements into a single virtual environment.
* Perform all `mamba` clean actions in the same layer as mamba install to help decrease image size.
- This is only applied to instances in which `mamba install` is used during the image build. If not, then instances of `mamba clean` are left in place to avoid noisy diffs that would be cosmetic to the image size.
> fix: Require cabinetry v0.5.1+

- docs/cc_packages.rst
- setup.py
Use 'req@url' syntax when using pip to install from a remote git repository over 'url#egg=req' to avoid the use of #egg= fragments with a non-PEP 508 name. This will be required in pip v25.0+.
- c.f. https://github.com/pypa/pip/pull/11617 for more details.
Also use `pip`'s `git+https` VCS scheme over `git+git` as recommended in the [`pip` docs on VCS Support](https://pip.pypa.io/en/stable/topics/vcs-support/):
> The use of `git`, `git+git`, and `git+http` schemes is discouraged. The former two use the Git Protocol, which lacks authentication, and HTTP is insecure due to lack of TLS based encryption.
> fix: Use 'req@url' syntax to install from remote VCS

- docs/cc_packages.rst
Just a simpe update to use PipInstall now that it's available on coffea-casa. I use it [like this](https://github.com/btcardwell/SIDM/blob/4396c5a477b52dcf38e2994ae76f467b646b2db5/sidm/tools/scaleout.py) in my analysis repo.
Fix https://github.com/CoffeaTeam/coffea-casa/issues/375
> Update packages docs to use dask.distributed.PipInstall

- docker/Dockerfile.cc-analysis-centos7
- docker/Dockerfile.cc-analysis-ubuntu
- docker/Dockerfile.cc-base-centos7
- docker/Dockerfile.cc-base-ubuntu
Resolves #379
Conda-forge `scipy` distributions seem to have a problem with optimizations that can cause `pyhf` inference to hang up to `scipy` `v1.8.1` where this seems to be resolved. This problem does NOT exist in wheel distributions on PyPI. To resolve this, simply set a lower bound on `scipy` of `v1.8.1`.
> fix: Require scipy v1.8.1+ from conda-forge

- coffea_casa/coffea_casa.py
- docker/Dockerfile.cc-analysis-ubuntu
- docker/Dockerfile.cc-ubuntu
- docker/prepare-env/prepare-env-cc-analysis.sh
A simple test for custom CoffeaCasa dask cluster (it will possibly not work for Dask Labextention)
See: https://github.com/CoffeaTeam/coffea-casa/issues/349
> Add support for mlflow token to be shipped over condor

- .pre-commit-config.yaml
- .readthedocs.yml
- pyproject.toml
- setup.cfg
Trying to follow https://scikit-hep.org/developer/reporeview to check the style of coffea-casa.git GitHub repository
> Fix style checks for coffea-casa repo

- docker/dask/dask.yaml
Having `terminate: 0` causes workers to be immediately terminated
```
distributed.nanny.memory - WARNING - Worker tls://192.168.204.84:34937 (pid=129) exceeded 0% memory budget. Restarting...
```
> Set dask distributed worker memory settings to recommendation for NERSC Cori

- docker/Dockerfile.cc-dask-alma8
I don't know if this is the best thing to do, but it works for now.
> naive chmod'ing to get permissions correct on certificates

- docker/prepare-env/prepare-env-cc-analysis.sh
We run HTCondor within Kubernetes, and when hostNetwork is not enabled, the RemoteHost reported by a Condor job defaults to the hostname of the worker node. However, what we actually need here is the IP address of the HTCondor pod itself.
Fortunately, this IP address is available via the StartdIpAddr classad. By utilizing StartdIpAddr, we ensure the Dask Worker has the correct contact address.
This change is designed to work seamlessly across different deployment scenarios—whether HTCondor is running outside Kubernetes, within Kubernetes with hostNetwork enabled, or in Kubernetes without hostNetwork.
> update HOST - daskworker contact addr

- docker/Dockerfile.cc-analysis-alma9
- docker/Dockerfile.cc-dask-alma9
- docker/prepare-env/prepare-env-cc-analysis.sh
We map user to local users.  So we need this fix-permission to run at a later stage so that the users can update those conda packages. 
```
$ ls -ld /usr/local/lib/python3.12/site-packages/numpy-1.26.4.dist-info/
drwxr-sr-x. 2 atlas-coffea atlas-coffea 4096 Mar  5 16:28 /usr/local/lib/python3.12/site-packages/numpy-1.26.4.dist-info/
$ groups
atlas-coffea
```
> add fix-permissions

- docker/prepare-env/prepare-env-cc-analysis.sh
- scripts-extra/submit_vine_workers_to_condor
Enable debug flag, and a script to submit vine workers in coffea-casa setting the correct worker type and container services.
> Vine worker add ons

- docker/Dockerfile.cc-analysis-alma9
- docker/Dockerfile.cc-analysis-combine-alma9
- docker/Dockerfile.cc-dask-alma9
- docker/Dockerfile.cc-dask-combine-alma9
A new Coffea image version has been detected.
This PR updates all Dockerfiles that use `coffeateam/coffea-dask-almalinux9-noml:<old>` to `coffeateam/coffea-dask-almalinux9-noml:2025.10.0-py3.12`.
> chore: update base image to coffeateam/coffea-dask-almalinux9-noml:2025.10.0-py3.12
